### ISSUE TITLE
Question about handle lifetime

### ISSUE THREAD

**Issue by yamt** [WebAssembly/wasi-nn#22]
how long will handles (graphs and execution context) be valid?
there seems to be no way to `close` them explicitly.
otoh, keeping them forever is not desirable i guess.

**Comment by abrown** [comment]
I guess implicitly they are tied to a WebAssembly instance. For users that may want instances that outlive the graph and execution context handles, however, it does make sense to add a way to close them. I briefly considered whether resource destruction should be handled at some other level (e.g., canonical ABI) but with the help of [this presentation](https://docs.google.com/presentation/d/1ikwS2Ps-KLXFofuS5VAs6Bn14q4LBEaxMjPfLj61UZE/edit#slide=id.gb40360eb39_0_208) came to the conclusion that the destructors should be explicit. @sunfishcode, is my understanding of those slides still correct?

**Comment by yamt** [comment]
`wit-bindgen c -i` generates `wasi_nn_graph_free`, which calls `canonical_abi.resource_drop_graph`.
ditto for `graph-execution-context`.
is it supposed to serve the purpose?

**Comment by tonibofarull** [comment]
With `wit-bindgen-cli 0.3.0 (04da8c228 2022-12-12)` I get the following error:

> failed to parse wit file `wasi-nn.wit`
> 
> Caused by:
>     expected `default`, `world` or `interface`, found keyword `type`
>          --> wasi-nn.wit:5:1
>           |
>         5 | type tensor-dimensions = list<u32>
>           | ^---
> error: Invalid value 'wasi-nn.wit' for '<DOCUMENT>': failed to parse wit file `wasi-nn.wit`

**Comment by abrown** [comment]
I think my response over [here](https://github.com/bytecodealliance/wasi-nn/issues/75#issuecomment-1370152817) refers to this. 

I believe the original question has been answered &mdash; `wit-bindgen` should provide a way to destroy resources &mdash; so I'm going to close this.
