### ISSUE TITLE
Add versioning to the WIT specification

### ISSUE THREAD

**Issue by devigned** [WebAssembly/wasi-nn#71]
To provide stability of the interfaces as it progresses, I believe we should add versioning to the WASI-NN wit package. This would enable consumers of the interface to specify the version of the interface that is implemented.

I propose we start with `package wasi:nn@0.2.0;` and progress from there.

**Comment by abrown** [comment]
Do you want to open a PR to do that?

**Comment by devigned** [comment]
> Do you want to open a PR to do that?

That is my intention. Just creating the issue first.
